# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/data.proto\"4\n\x06\x43ourse\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08semester\x18\x03 \x01(\t\"&\n\nCourseList\x12\x18\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x07.Course\"!\n\x05Major\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"4\n\tProfessor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x66irst\x18\x02 \x01(\t\x12\x0c\n\x04last\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COURSE._serialized_start=20
  _COURSE._serialized_end=72
  _COURSELIST._serialized_start=74
  _COURSELIST._serialized_end=112
  _MAJOR._serialized_start=114
  _MAJOR._serialized_end=147
  _PROFESSOR._serialized_start=149
  _PROFESSOR._serialized_end=201
# @@protoc_insertion_point(module_scope)
