# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/data.proto\"4\n\x06\x43ourse\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08semester\x18\x03 \x01(\t\"!\n\x05Major\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"4\n\tProfessor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x66irst\x18\x02 \x01(\t\x12\x0c\n\x04last\x18\x03 \x01(\tb\x06proto3')



_COURSE = DESCRIPTOR.message_types_by_name['Course']
_MAJOR = DESCRIPTOR.message_types_by_name['Major']
_PROFESSOR = DESCRIPTOR.message_types_by_name['Professor']
Course = _reflection.GeneratedProtocolMessageType('Course', (_message.Message,), {
  'DESCRIPTOR' : _COURSE,
  '__module__' : 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:Course)
  })
_sym_db.RegisterMessage(Course)

Major = _reflection.GeneratedProtocolMessageType('Major', (_message.Message,), {
  'DESCRIPTOR' : _MAJOR,
  '__module__' : 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:Major)
  })
_sym_db.RegisterMessage(Major)

Professor = _reflection.GeneratedProtocolMessageType('Professor', (_message.Message,), {
  'DESCRIPTOR' : _PROFESSOR,
  '__module__' : 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:Professor)
  })
_sym_db.RegisterMessage(Professor)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COURSE._serialized_start=20
  _COURSE._serialized_end=72
  _MAJOR._serialized_start=74
  _MAJOR._serialized_end=107
  _PROFESSOR._serialized_start=109
  _PROFESSOR._serialized_end=161
# @@protoc_insertion_point(module_scope)
