# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/requests.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import data_pb2 as proto_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/requests.proto\x1a\x10proto/data.proto\">\n\x13NotificationRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x18\n\x07\x63lasses\x18\x02 \x03(\x0b\x32\x07.Course\"\x96\x02\n\x0fScheduleRequest\x12\x15\n\x05major\x18\x01 \x01(\x0b\x32\x06.Major\x12\x10\n\x08semester\x18\x02 \x01(\t\x12\x12\n\nminCredits\x18\x03 \x01(\x05\x12\x12\n\nmaxCredits\x18\x04 \x01(\x05\x12 \n\x0fpreviousClasses\x18\x05 \x03(\x0b\x32\x07.Course\x12!\n\x10preferredClasses\x18\x06 \x03(\x0b\x32\x07.Course\x12#\n\x12unpreferredClasses\x18\x07 \x03(\x0b\x32\x07.Course\x12\"\n\x0epreferredProfs\x18\x08 \x03(\x0b\x32\n.Professor\x12$\n\x10unprefferedProfs\x18\t \x03(\x0b\x32\n.Professor\"\x0e\n\x0cMajorRequest\"\x12\n\x10ProfessorRequest\"\x0f\n\rCourseRequest\"\x1b\n\x0c\x44\x65\x62ugRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\xf5\x01\n\x07Request\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.RequestType\x12\x1e\n\x02r1\x18\x02 \x01(\x0b\x32\x10.ScheduleRequestH\x00\x12\"\n\x02r2\x18\x03 \x01(\x0b\x32\x14.NotificationRequestH\x00\x12\x1f\n\x02r3\x18\x04 \x01(\x0b\x32\x11.ProfessorRequestH\x00\x12\x1c\n\x02r4\x18\x05 \x01(\x0b\x32\x0e.CourseRequestH\x00\x12\x1b\n\x02r5\x18\x06 \x01(\x0b\x32\r.DebugRequestH\x00\x12\x1b\n\x02r6\x18\x07 \x01(\x0b\x32\r.MajorRequestH\x00\x12\n\n\x02id\x18\x08 \x01(\x05\x42\x05\n\x03msg*v\n\x0bRequestType\x12\x10\n\x0cREQ_SCHEDULE\x10\x00\x12\x14\n\x10REQ_NOTIFICATION\x10\x01\x12\x11\n\rREQ_PROFESSOR\x10\x02\x12\x0e\n\nREQ_COURSE\x10\x03\x12\r\n\tREQ_DEBUG\x10\x04\x12\r\n\tREQ_MAJOR\x10\x05\x62\x06proto3')

_REQUESTTYPE = DESCRIPTOR.enum_types_by_name['RequestType']
RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
REQ_SCHEDULE = 0
REQ_NOTIFICATION = 1
REQ_PROFESSOR = 2
REQ_COURSE = 3
REQ_DEBUG = 4
REQ_MAJOR = 5


_NOTIFICATIONREQUEST = DESCRIPTOR.message_types_by_name['NotificationRequest']
_SCHEDULEREQUEST = DESCRIPTOR.message_types_by_name['ScheduleRequest']
_MAJORREQUEST = DESCRIPTOR.message_types_by_name['MajorRequest']
_PROFESSORREQUEST = DESCRIPTOR.message_types_by_name['ProfessorRequest']
_COURSEREQUEST = DESCRIPTOR.message_types_by_name['CourseRequest']
_DEBUGREQUEST = DESCRIPTOR.message_types_by_name['DebugRequest']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
NotificationRequest = _reflection.GeneratedProtocolMessageType('NotificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONREQUEST,
  '__module__' : 'proto.requests_pb2'
  # @@protoc_insertion_point(class_scope:NotificationRequest)
  })
_sym_db.RegisterMessage(NotificationRequest)

ScheduleRequest = _reflection.GeneratedProtocolMessageType('ScheduleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULEREQUEST,
  '__module__' : 'proto.requests_pb2'
  # @@protoc_insertion_point(class_scope:ScheduleRequest)
  })
_sym_db.RegisterMessage(ScheduleRequest)

MajorRequest = _reflection.GeneratedProtocolMessageType('MajorRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAJORREQUEST,
  '__module__' : 'proto.requests_pb2'
  # @@protoc_insertion_point(class_scope:MajorRequest)
  })
_sym_db.RegisterMessage(MajorRequest)

ProfessorRequest = _reflection.GeneratedProtocolMessageType('ProfessorRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROFESSORREQUEST,
  '__module__' : 'proto.requests_pb2'
  # @@protoc_insertion_point(class_scope:ProfessorRequest)
  })
_sym_db.RegisterMessage(ProfessorRequest)

CourseRequest = _reflection.GeneratedProtocolMessageType('CourseRequest', (_message.Message,), {
  'DESCRIPTOR' : _COURSEREQUEST,
  '__module__' : 'proto.requests_pb2'
  # @@protoc_insertion_point(class_scope:CourseRequest)
  })
_sym_db.RegisterMessage(CourseRequest)

DebugRequest = _reflection.GeneratedProtocolMessageType('DebugRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGREQUEST,
  '__module__' : 'proto.requests_pb2'
  # @@protoc_insertion_point(class_scope:DebugRequest)
  })
_sym_db.RegisterMessage(DebugRequest)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'proto.requests_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTTYPE._serialized_start=717
  _REQUESTTYPE._serialized_end=835
  _NOTIFICATIONREQUEST._serialized_start=42
  _NOTIFICATIONREQUEST._serialized_end=104
  _SCHEDULEREQUEST._serialized_start=107
  _SCHEDULEREQUEST._serialized_end=385
  _MAJORREQUEST._serialized_start=387
  _MAJORREQUEST._serialized_end=401
  _PROFESSORREQUEST._serialized_start=403
  _PROFESSORREQUEST._serialized_end=421
  _COURSEREQUEST._serialized_start=423
  _COURSEREQUEST._serialized_end=438
  _DEBUGREQUEST._serialized_start=440
  _DEBUGREQUEST._serialized_end=467
  _REQUEST._serialized_start=470
  _REQUEST._serialized_end=715
# @@protoc_insertion_point(module_scope)
