# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/responses.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import data_pb2 as proto_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/responses.proto\x1a\x10proto/data.proto\"&\n\nCourseList\x12\x18\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x07.Course\"\x87\x01\n\x10ScheduleResponse\x12\x34\n\ncourse_map\x18\x01 \x03(\x0b\x32 .ScheduleResponse.CourseMapEntry\x1a=\n\x0e\x43ourseMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.CourseList:\x02\x38\x01\"3\n\x11ProfessorResponse\x12\x1e\n\nprofessors\x18\x01 \x03(\x0b\x32\n.Professor\"*\n\x0e\x43ourseResponse\x12\x18\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x07.Course\"\x1c\n\rDebugResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\'\n\rMajorResponse\x12\x16\n\x06majors\x18\x01 \x03(\x0b\x32\x06.Major\"\'\n\x14NotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.responses_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCHEDULERESPONSE_COURSEMAPENTRY._options = None
  _SCHEDULERESPONSE_COURSEMAPENTRY._serialized_options = b'8\001'
  _COURSELIST._serialized_start=43
  _COURSELIST._serialized_end=81
  _SCHEDULERESPONSE._serialized_start=84
  _SCHEDULERESPONSE._serialized_end=219
  _SCHEDULERESPONSE_COURSEMAPENTRY._serialized_start=158
  _SCHEDULERESPONSE_COURSEMAPENTRY._serialized_end=219
  _PROFESSORRESPONSE._serialized_start=221
  _PROFESSORRESPONSE._serialized_end=272
  _COURSERESPONSE._serialized_start=274
  _COURSERESPONSE._serialized_end=316
  _DEBUGRESPONSE._serialized_start=318
  _DEBUGRESPONSE._serialized_end=346
  _MAJORRESPONSE._serialized_start=348
  _MAJORRESPONSE._serialized_end=387
  _NOTIFICATIONRESPONSE._serialized_start=389
  _NOTIFICATIONRESPONSE._serialized_end=428
# @@protoc_insertion_point(module_scope)
