# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: class.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63lass.proto\"!\n\x05\x43lass\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x13\n\x05Major\x12\n\n\x02id\x18\x01 \x01(\x05\"4\n\tProfessor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x66irst\x18\x02 \x01(\t\x12\x0c\n\x04last\x18\x03 \x01(\t\"=\n\x13NotificationRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x17\n\x07\x63lasses\x18\x02 \x03(\x0b\x32\x06.Class\"\xd1\x01\n\x0fScheduleRequest\x12\r\n\x05major\x18\x01 \x01(\t\x12\x1f\n\x0fpreviousClasses\x18\x02 \x03(\x0b\x32\x06.Class\x12 \n\x10preferredClasses\x18\x03 \x03(\x0b\x32\x06.Class\x12\"\n\x12unpreferredClasses\x18\x04 \x03(\x0b\x32\x06.Class\x12\"\n\x0epreferredProfs\x18\x05 \x03(\x0b\x32\n.Professor\x12$\n\x10unprefferedProfs\x18\x06 \x03(\x0b\x32\n.Professor\"\x12\n\x10ScheduleResponseb\x06proto3')



_CLASS = DESCRIPTOR.message_types_by_name['Class']
_MAJOR = DESCRIPTOR.message_types_by_name['Major']
_PROFESSOR = DESCRIPTOR.message_types_by_name['Professor']
_NOTIFICATIONREQUEST = DESCRIPTOR.message_types_by_name['NotificationRequest']
_SCHEDULEREQUEST = DESCRIPTOR.message_types_by_name['ScheduleRequest']
_SCHEDULERESPONSE = DESCRIPTOR.message_types_by_name['ScheduleResponse']
Class = _reflection.GeneratedProtocolMessageType('Class', (_message.Message,), {
  'DESCRIPTOR' : _CLASS,
  '__module__' : 'class_pb2'
  # @@protoc_insertion_point(class_scope:Class)
  })
_sym_db.RegisterMessage(Class)

Major = _reflection.GeneratedProtocolMessageType('Major', (_message.Message,), {
  'DESCRIPTOR' : _MAJOR,
  '__module__' : 'class_pb2'
  # @@protoc_insertion_point(class_scope:Major)
  })
_sym_db.RegisterMessage(Major)

Professor = _reflection.GeneratedProtocolMessageType('Professor', (_message.Message,), {
  'DESCRIPTOR' : _PROFESSOR,
  '__module__' : 'class_pb2'
  # @@protoc_insertion_point(class_scope:Professor)
  })
_sym_db.RegisterMessage(Professor)

NotificationRequest = _reflection.GeneratedProtocolMessageType('NotificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONREQUEST,
  '__module__' : 'class_pb2'
  # @@protoc_insertion_point(class_scope:NotificationRequest)
  })
_sym_db.RegisterMessage(NotificationRequest)

ScheduleRequest = _reflection.GeneratedProtocolMessageType('ScheduleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULEREQUEST,
  '__module__' : 'class_pb2'
  # @@protoc_insertion_point(class_scope:ScheduleRequest)
  })
_sym_db.RegisterMessage(ScheduleRequest)

ScheduleResponse = _reflection.GeneratedProtocolMessageType('ScheduleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULERESPONSE,
  '__module__' : 'class_pb2'
  # @@protoc_insertion_point(class_scope:ScheduleResponse)
  })
_sym_db.RegisterMessage(ScheduleResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLASS._serialized_start=15
  _CLASS._serialized_end=48
  _MAJOR._serialized_start=50
  _MAJOR._serialized_end=69
  _PROFESSOR._serialized_start=71
  _PROFESSOR._serialized_end=123
  _NOTIFICATIONREQUEST._serialized_start=125
  _NOTIFICATIONREQUEST._serialized_end=186
  _SCHEDULEREQUEST._serialized_start=189
  _SCHEDULEREQUEST._serialized_end=398
  _SCHEDULERESPONSE._serialized_start=400
  _SCHEDULERESPONSE._serialized_end=418
# @@protoc_insertion_point(module_scope)
